services:
  - type: web
    name: bot-haze-monkeyz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MINI_APP_URL
        sync: false
      - key: INSTAGRAM_URL
        sync: false
      - key: WHATSAPP_URL
        sync: false
      - key: TELEGRAM_CHANNEL_URL
        sync: false
      - key: TELEGRAM_RETURN_URL
        sync: false
      - key: IMAGE_PATH
        value: monkeys_logo.png
      - key: USERS_FILE
        value: users.json

